name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up pnpm 
        uses: pnpm/action-setup@v3

      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: pnpm i

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Run linter
        run: pnpm lint